version: '3.3'
services:
  postgres:
    image: postgres:15
    container_name: postgres_restaurantes
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restaurantedb
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservas_restaurantes
    ports:
      - 8080:80
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_restaurantes:5432/restaurantedb
      SPRING_DATASOURCE_USERNAME: bruno
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
